/**
 * ============================================================
 *  PORTFOLIO — app.js
 *  Reads content from content.js and renders the entire site.
 *  DO NOT EDIT THIS FILE to update content.
 *  Only edit content.js.
 * ============================================================
 */

'use strict';

// ── SVG ICONS ─────────────────────────────────────────────
const ICONS = {
  code:       `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>`,
  smartphone: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="5" y="2" width="14" height="20" rx="2" ry="2"/><line x1="12" y1="18" x2="12.01" y2="18"/></svg>`,
  layers:     `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 2 7 12 12 22 7 12 2"/><polyline points="2 17 12 22 22 17"/><polyline points="2 12 12 17 22 12"/></svg>`,
  zap:        `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>`,
  wifi:       `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12.55a11 11 0 0 1 14.08 0"/><path d="M1.42 9a16 16 0 0 1 21.16 0"/><path d="M8.53 16.11a6 6 0 0 1 6.95 0"/><line x1="12" y1="20" x2="12.01" y2="20"/></svg>`,
  server:     `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="2" width="20" height="8" rx="2" ry="2"/><rect x="2" y="14" width="20" height="8" rx="2" ry="2"/><line x1="6" y1="6" x2="6.01" y2="6"/><line x1="6" y1="18" x2="6.01" y2="18"/></svg>`,
  cpu:        `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="4" width="16" height="16" rx="2" ry="2"/><rect x="9" y="9" width="6" height="6"/><line x1="9" y1="1" x2="9" y2="4"/><line x1="15" y1="1" x2="15" y2="4"/><line x1="9" y1="20" x2="9" y2="23"/><line x1="15" y1="20" x2="15" y2="23"/><line x1="20" y1="9" x2="23" y2="9"/><line x1="20" y1="14" x2="23" y2="14"/><line x1="1" y1="9" x2="4" y2="9"/><line x1="1" y1="14" x2="4" y2="14"/></svg>`,
  shield:     `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>`,
  'git-branch': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="6" y1="3" x2="6" y2="15"/><circle cx="18" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><path d="M18 9a9 9 0 0 1-9 9"/></svg>`,
  database:   `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3"/><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"/></svg>`,
  award:      `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8" r="7"/><polyline points="8.21 13.89 7 23 12 20 17 23 15.79 13.88"/></svg>`,
  star:       `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>`,
  trophy:     `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="8 17 12 22 16 17"/><line x1="12" y1="12" x2="12" y2="22"/><path d="M20 6H4"/><path d="M17 6a5 5 0 0 1-10 0V2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1Z"/><path d="M2 2h2v4a4 4 0 0 0 4 4"/><path d="M22 2h-2v4a4 4 0 0 1-4 4"/></svg>`,
  linkedin:   `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"/><rect x="2" y="9" width="4" height="12"/><circle cx="4" cy="4" r="2"/></svg>`,
  github:     `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"/></svg>`,
  mail:       `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/></svg>`,
  phone:      `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07A19.5 19.5 0 0 1 4.69 13.6a19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 3.6 2.76l3-.01a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L7.91 9.4a16 16 0 0 0 6.29 6.29l.86-.87a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"/></svg>`,
  'map-pin':  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"/><circle cx="12" cy="10" r="3"/></svg>`,
  download:   `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>`,
  'external-link': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><polyline points="15 3 21 3 21 9"/><line x1="10" y1="14" x2="21" y2="3"/></svg>`,
  'git-merge': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="18" cy="18" r="3"/><circle cx="6" cy="6" r="3"/><path d="M6 21V9a9 9 0 0 0 9 9"/></svg>`,
  briefcase:  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="7" width="20" height="14" rx="2" ry="2"/><path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"/></svg>`,
  calendar:   `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg>`,
  arrow:      `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>`,
  'arrow-up': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="19" x2="12" y2="5"/><polyline points="5 12 12 5 19 12"/></svg>`,
  check:      `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"/></svg>`,
  'git-commit': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"/><line x1="1.05" y1="12" x2="7" y2="12"/><line x1="17.01" y1="12" x2="22.96" y2="12"/></svg>`,
};

function icon(name, cls = '') {
  return `<span class="icon ${cls}" aria-hidden="true">${ICONS[name] || ICONS.code}</span>`;
}

// ── DATE UTILITIES ─────────────────────────────────────────
function parseYearMonth(str) {
  if (!str) return null;
  const parts = str.split('-');
  return new Date(parseInt(parts[0]), parseInt(parts[1] || 1) - 1, 1);
}

function getDynamicYears(startDateStr) {
  const start = parseYearMonth(startDateStr);
  if (!start) return '3';
  const now = new Date();
  const years = (now - start) / (1000 * 60 * 60 * 24 * 365.25);
  return Math.floor(years).toString();
}

function formatPeriod(period) {
  if (!period) return '';
  if (typeof period === 'string') return period;
  const start = parseYearMonth(period.start);
  const end   = period.end ? parseYearMonth(period.end) : null;
  const fmtOpts = { month: 'short', year: 'numeric' };
  const startStr = start ? start.toLocaleDateString('en-US', fmtOpts) : '';
  const endStr   = end   ? end.toLocaleDateString('en-US', fmtOpts) : 'Present';
  return `${startStr} – ${endStr}`;
}

function getDurationMonths(period) {
  if (!period || typeof period === 'string') return '';
  const start = parseYearMonth(period.start);
  const end   = period.end ? parseYearMonth(period.end) : new Date();
  if (!start) return '';
  const months = Math.round((end - start) / (1000 * 60 * 60 * 24 * 30.44));
  const years  = Math.floor(months / 12);
  const rem    = months % 12;
  if (years > 0 && rem > 0) return `${years}y ${rem}m`;
  if (years > 0) return `${years}y`;
  return `${months}m`;
}

// ── HELPERS ────────────────────────────────────────────────
function esc(str) {
  const el = document.createElement('div');
  el.textContent = str;
  return el.innerHTML;
}

function resolveStatValue(stat, content) {
  if (stat.value === 'dynamic:experience') {
    return getDynamicYears(content.personal.experienceStartDate);
  }
  return stat.value;
}

// ── RENDER: NAV ────────────────────────────────────────────
function renderNav(content) {
  const { nav, personal } = content;
  const links = nav.links.map(l =>
    `<a class="nav__link" href="${l.href}" data-href="${l.href}">${esc(l.label)}</a>`
  ).join('');

  const picHtml = personal.profilePic
    ? `<img src="${personal.profilePic}" alt="${esc(personal.name)}" class="nav__profile-pic" />`
    : '';

  document.getElementById('nav').innerHTML = `
    <div class="nav__inner">
      <a class="nav__logo" href="#hero">
        ${picHtml}
        <span class="nav__logo-text">${esc(nav.logo)}</span>
      </a>
      <nav class="nav__links" aria-label="Main navigation">
        ${links}
        <a class="nav__link nav__cta" href="${personal.resumeDownload}" target="_blank" rel="noopener">
          ${icon('download', 'btn-icon')} Resume
        </a>
      </nav>
      <button class="nav__hamburger" id="hamburger" type="button" aria-label="Toggle menu" aria-expanded="false">
        <span></span><span></span><span></span>
      </button>
    </div>
    <nav class="nav__mobile" id="mobileMenu" aria-label="Mobile navigation">
      ${nav.links.map(l => `<a class="nav__link" href="${l.href}">${esc(l.label)}</a>`).join('')}
      <a class="nav__link" href="${personal.resumeDownload}" target="_blank" rel="noopener">
        ${icon('download', 'btn-icon')} Resume
      </a>
    </nav>
  `;
}

// ── RENDER: HERO ───────────────────────────────────────────
function renderHero(content) {
  const { personal } = content;

  const statsHtml = personal.stats.map((s, i) => `
    <div class="hero__stat reveal reveal-delay-${i+2}">
      <span class="hero__stat-value" data-target="${resolveStatValue(s, content)}" data-suffix="${s.suffix || ''}">0</span>
      <span class="hero__stat-label">${esc(s.label)}</span>
    </div>
  `).join('');

  const picHtml = personal.profilePic ? `
    <div class="hero__pic-wrap reveal-right">
      <img src="${personal.profilePic}" alt="${esc(personal.name)}" class="hero__pic" />
    </div>
  ` : '';

  document.getElementById('hero').innerHTML = `
    <div class="hero__bg">
      <div class="hero__grid"></div>
      <div class="hero__orb hero__orb--1"></div>
      <div class="hero__orb hero__orb--2"></div>
      <div class="hero__orb hero__orb--3"></div>
    </div>
    <div class="container">
      <div class="hero__layout">
        <div class="hero__content">
          <h1 class="hero__name reveal">
            ${esc(personal.name.split(' ').slice(0, 2).join(' '))} <br>
            <span class="hero__name-gradient">${esc(personal.name.split(' ').slice(2).join(' '))}</span>
          </h1>
          <div class="hero__title-wrap reveal reveal-delay-1">
            <span class="hero__typing" id="typingText" aria-live="polite"></span>
            <span class="hero__cursor" aria-hidden="true"></span>
          </div>
          <div class="hero__availability reveal reveal-delay-2">
            <span class="hero__badge-dot"></span>
            ${esc(personal.availability)}
          </div>
          <p class="hero__subtitle reveal reveal-delay-2">${esc(personal.heroSubtitle)}</p>
          <div class="hero__social reveal reveal-delay-3">
            <a class="social-link" href="${personal.linkedin}" target="_blank" rel="noopener" aria-label="LinkedIn" title="LinkedIn">
              ${icon('linkedin')} <span>LinkedIn</span>
            </a>
            <a class="social-link" href="${personal.github}" target="_blank" rel="noopener" aria-label="GitHub" title="GitHub">
              ${icon('github')} <span>GitHub</span>
            </a>
            <a class="social-link" href="mailto:${personal.email}" aria-label="Email" title="Email">
              ${icon('mail')} <span>Email</span>
            </a>
            <a class="social-link" href="tel:${personal.phone}" aria-label="Phone" title="Phone">
              ${icon('phone')} <span>Call</span>
            </a>
          </div>
          <div class="hero__actions reveal reveal-delay-3">
            <a class="btn btn-primary" href="#projects">
              ${icon('arrow', 'btn-icon')} View Projects
            </a>
            <a class="btn btn-secondary" href="#contact">
              ${icon('mail', 'btn-icon')} Let's Connect
            </a>
            <a class="btn btn-outline" href="${personal.resumeDownload}" target="_blank" rel="noopener">
              ${icon('download', 'btn-icon')} Download CV
            </a>
          </div>
          <div class="hero__stats">
            ${statsHtml}
          </div>
        </div>
        ${picHtml}
      </div>
    </div>
  `;
}

// ── RENDER: ABOUT ──────────────────────────────────────────
function renderAbout(content) {
  const { about, personal } = content;

  const paragraphs = about.paragraphs.map(p =>
    `<p>${esc(p)}</p>`
  ).join('');

  const cards = about.highlights.map((h, i) => `
    <div class="about__highlight-card reveal reveal-delay-${i+1}">
      <div class="about__card-icon-wrap">
        <div class="about__card-icon">${icon(h.icon)}</div>
      </div>
      <div class="about__card-body">
        <h4>${esc(h.label)}</h4>
        <p>${esc(h.desc)}</p>
      </div>
    </div>
  `).join('');

  document.getElementById('about').innerHTML = `
    <div class="container">
      <div class="section-header">
        <div class="section-label">${icon('code')} About Me</div>
        <h2 class="section-title">Passionate about engineering<br>elegant mobile experiences</h2>
      </div>
      <div class="about__grid">
        <div class="about__text reveal-left">
          <div class="about__intro-badge">
            <span class="about__intro-badge-dot"></span>
            ${esc(personal.availability)}
          </div>
          <h3>Hey, I'm <span class="about__name-highlight">${esc(personal.name.split(' ')[0])}</span> 👋</h3>
          <p class="about__lead">${esc(about.intro)}</p>
          ${paragraphs}
          <div class="about__meta-row">
            <span class="about__meta-chip">${icon('map-pin')} ${esc(personal.location)}</span>
            <span class="about__meta-chip">${icon('briefcase')} 3+ Years Experience</span>
          </div>
          <div class="about__cta-row">
            <a class="btn btn-primary" href="#contact">${icon('mail','btn-icon')} Hire Me</a>
            <a class="btn btn-secondary" href="${personal.resumeDownload}" target="_blank" rel="noopener">${icon('download','btn-icon')} Resume</a>
          </div>
        </div>
        <div class="about__highlights reveal-right">
          ${cards}
        </div>
      </div>
    </div>
  `;
}

// ── RENDER: SKILLS ─────────────────────────────────────────
// Proficiency levels (percentage) for each category
const SKILL_PROFICIENCY = {
  'Languages': 90,
  'Android': 97,
  'Architecture': 95,
  'Libraries & Networking': 92,
  'Real-time & Firebase': 88,
  'Testing': 85,
  'DevOps & Tools': 80,
  'AI / ML': 75,
};

function renderSkills(content) {
  const cards = content.skills.map((cat, i) => {
    const bgColor = cat.color + '18';
    const fgColor = cat.color;
    const proficiency = SKILL_PROFICIENCY[cat.category] || 80;

    const skillItems = cat.items.map(item => `
      <div class="skill-item">
        <div class="skill-item__header">
          <span class="skill-item__name">${esc(item)}</span>
        </div>
        <div class="skill-bar">
          <div class="skill-bar__fill" style="--bar-color:${fgColor}" data-width="${Math.max(55, proficiency - Math.floor(Math.random()*15))}"></div>
        </div>
      </div>
    `).join('');

    return `
      <div class="skill-card reveal reveal-delay-${(i % 5) + 1}" style="--cat-color:${fgColor}; --cat-bg:${bgColor}">
        <div class="skill-card__header">
          <div class="skill-card__icon-wrap" style="background:${bgColor}; color:${fgColor}">
            ${icon(cat.icon)}
          </div>
          <div class="skill-card__title-group">
            <span class="skill-card__title">${esc(cat.category)}</span>
            <span class="skill-card__pct" style="color:${fgColor}">${proficiency}%</span>
          </div>
        </div>
        <div class="skill-card__master-bar">
          <div class="skill-card__master-fill" style="--bar-color:${fgColor}; --bar-width:${proficiency}%"></div>
        </div>
        <div class="skill-items">${skillItems}</div>
      </div>
    `;
  }).join('');

  document.getElementById('skills').innerHTML = `
    <div class="container">
      <div class="section-header">
        <div class="section-label">${icon('zap')} Technical Skills</div>
        <h2 class="section-title">My Technology Arsenal</h2>
        <p class="section-subtitle">Production-tested tools & technologies with real-world proficiency.</p>
      </div>
      <div class="skills__grid">${cards}</div>
    </div>
  `;

  // Animate bars on scroll into view
  requestAnimationFrame(() => {
    const bars = document.querySelectorAll('.skill-bar__fill, .skill-card__master-fill');
    const obs = new IntersectionObserver((entries) => {
      entries.forEach(e => {
        if (e.isIntersecting) {
          const el = e.target;
          const w = el.dataset.width || el.style.getPropertyValue('--bar-width');
          el.style.width = typeof w === 'string' && w.includes('%') ? w : w + '%';
          obs.unobserve(el);
        }
      });
    }, { threshold: 0.2 });
    bars.forEach(b => obs.observe(b));
  });
}

// ── RENDER: EXPERIENCE ─────────────────────────────────────
function renderExperience(content) {
  const items = content.experience.map((exp, i) => {
    const highlights = exp.highlights.map(h =>
      `<li class="timeline-highlight">${esc(h)}</li>`
    ).join('');

    const techTags = (exp.techStack || []).map(t =>
      `<span class="skill-tag">${esc(t)}</span>`
    ).join('');

    const duration = getDurationMonths(exp.period);
    const typeBadge = exp.type ? `<span class="exp-type-badge">${esc(exp.type)}</span>` : '';

    return `
      <div class="timeline-item">
        <div class="timeline-dot">
          <div class="timeline-dot__circle">${icon('briefcase')}</div>
        </div>
        <div class="timeline-card reveal reveal-delay-${i+1}">
          <div class="timeline-card__header">
            <div>
              <div class="timeline-card__role">${esc(exp.role)}</div>
              <div class="timeline-card__company">${esc(exp.company)} ${typeBadge}</div>
            </div>
            <div class="timeline-card__meta">
              <div class="timeline-badge">
                ${icon('calendar')} ${formatPeriod(exp.period)}${duration ? ` · ${duration}` : ''}
              </div>
              <div class="timeline-card__location">${icon('map-pin')} ${esc(exp.location)}</div>
            </div>
          </div>
          <ul class="timeline-highlights">${highlights}</ul>
          ${techTags ? `<div class="timeline-tech">${techTags}</div>` : ''}
        </div>
      </div>
    `;
  }).join('');

  document.getElementById('experience').innerHTML = `
    <div class="container">
      <div class="section-header">
        <div class="section-label">${icon('briefcase')} Experience</div>
        <h2 class="section-title">Professional Journey</h2>
        <p class="section-subtitle">Building impactful products at scale with measurable results.</p>
      </div>
      <div class="timeline">${items}</div>
    </div>
  `;
}

// ── RENDER: PROJECTS ───────────────────────────────────────
function renderProjects(content) {
  // Merge all projects into one unified grid
  const allProjects = content.projects;

  function projectCard(p) {
    const tags    = p.tags.map(t => `<span class="skill-tag">${esc(t)}</span>`).join('');
    const metrics = (p.metrics || []).map(m => `<span class="project-metric">${icon('check')} ${esc(m)}</span>`).join('');
    const bullets = p.highlights.slice(0, 4).map(h =>
      `<li class="project-highlight">${esc(h)}</li>`
    ).join('');
    const links = [
      p.githubUrl ? `<a class="project-link" href="${p.githubUrl}" target="_blank" rel="noopener">${icon('github')} GitHub</a>` : '',
      p.liveUrl   ? `<a class="project-link" href="${p.liveUrl}" target="_blank" rel="noopener">${icon('external-link')} Live</a>` : '',
    ].filter(Boolean).join('');

    return `
      <div class="project-card reveal">
        <div class="project-card__top-bar"></div>
        <div class="project-card__header">
          <div class="project-card__name-wrap">
            <div class="project-card__name">${esc(p.name)}</div>
            <div class="project-card__subtitle">${esc(p.subtitle)}</div>
          </div>
          <span class="project-card__period">${formatPeriod(p.period)}</span>
        </div>
        <p class="project-card__desc">${esc(p.description)}</p>
        <ul class="project-card__highlights">${bullets}</ul>
        ${metrics ? `<div class="project-card__metrics">${metrics}</div>` : ''}
        <div class="project-card__tags">${tags}</div>
        ${links ? `<div class="project-card__actions">${links}</div>` : ''}
      </div>
    `;
  }

  document.getElementById('projects').innerHTML = `
    <div class="container">
      <div class="section-header">
        <div class="section-label">${icon('layers')} Projects</div>
        <h2 class="section-title">What I've Built</h2>
        <p class="section-subtitle">Production-grade applications shipped for enterprise clients and real-world users.</p>
      </div>
      <div class="projects__all-grid">${allProjects.map(p => projectCard(p)).join('')}</div>
    </div>
  `;
}

// ── RENDER: AI SECTION ─────────────────────────────────────
function renderAI(content) {
  const { aiExperience } = content;

  const cards = aiExperience.items.map((item, i) => `
    <div class="ai-card reveal reveal-delay-${(i % 3) + 1}">
      <div class="ai-card__icon">${icon(item.icon)}</div>
      <h3>${esc(item.title)}</h3>
      <p>${esc(item.description)}</p>
      <div class="ai-tags">
        ${item.tags.map(t => `<span class="ai-tag">${esc(t)}</span>`).join('')}
      </div>
    </div>
  `).join('');

  document.getElementById('ai').innerHTML = `
    <div class="container">
      <div class="section-header">
        <div class="section-label">${icon('cpu')} AI & LLM</div>
        <h2 class="section-title" style="color:#F8FAFC">Generative AI & LLM Experience</h2>
        <p class="section-subtitle" style="color:#94A3B8">A dedicated discipline — not a buzzword.</p>
      </div>
      <div style="text-align:center;">
        <div class="ai-badge reveal">${icon('zap')} ${esc(aiExperience.badge)}</div>
      </div>
      <p class="ai-intro reveal">${esc(aiExperience.intro)}</p>
      <div class="ai-grid">${cards}</div>
    </div>
  `;
}

// ── RENDER: OPEN SOURCE ─────────────────────────────────────
function renderOpenSource(content) {
  const cards = content.openSource.map(os => {
    const prTags = (os.prs || []).map(pr =>
      `<span class="os-pr-tag">${icon('git-commit')} PR ${esc(pr)}</span>`
    ).join('');
    const issueTags = (os.issues || []).map(iss =>
      `<span class="os-issue-tag">${icon('git-commit')} Issue ${esc(iss)}</span>`
    ).join('');
    const prSection = (prTags || issueTags) ? `
      <div class="os-contributions">
        ${prTags}${issueTags}
      </div>
    ` : '';

    return `
      <div class="opensource-card reveal">
        <div class="opensource-card__info">
          <div class="opensource-card__name">
            ${icon('github')}
            <h3>${esc(os.name)}</h3>
            ${os.stars ? `<span class="os-stars">${icon('star')} ${esc(os.stars)}</span>` : ''}
          </div>
          <p class="opensource-card__desc">${esc(os.description)}</p>
          ${prSection}
          <div class="project-card__tags">
            ${os.tags.map(t => `<span class="skill-tag">${esc(t)}</span>`).join('')}
          </div>
        </div>
        <div class="opensource-card__actions">
          <a class="btn btn-primary" href="${os.url}" target="_blank" rel="noopener">
            ${icon('github', 'btn-icon')} View on GitHub
          </a>
        </div>
      </div>
    `;
  }).join('');

  document.getElementById('opensource').innerHTML = `
    <div class="container">
      <div class="section-header">
        <div class="section-label">${icon('github')} Open Source</div>
        <h2 class="section-title">Open Source Contributions</h2>
        <p class="section-subtitle">Giving back to the developer community with real, merged contributions.</p>
      </div>
      <div class="opensource-grid">${cards}</div>
    </div>
  `;
}

// ── RENDER: ACHIEVEMENTS ───────────────────────────────────
const ACHIEVEMENT_GRADIENTS = [
  'linear-gradient(135deg,#2563EB,#7C3AED)',
  'linear-gradient(135deg,#0891B2,#2563EB)',
  'linear-gradient(135deg,#7C3AED,#EC4899)',
  'linear-gradient(135deg,#059669,#0891B2)',
  'linear-gradient(135deg,#D97706,#DC2626)',
  'linear-gradient(135deg,#2563EB,#059669)',
  'linear-gradient(135deg,#7C3AED,#2563EB)',
  'linear-gradient(135deg,#EC4899,#7C3AED)',
];
// Global fallback: called when a cert card image fails to load
window.certImgError = function(img) {
  const wrap = img.closest('.cert-card__img-wrap');
  if (wrap) {
    const ph = document.createElement('div');
    ph.className = 'cert-card__pdf-preview';
    ph.innerHTML = '<div class="cert-card__pdf-icon"><svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8" r="6"/><path d="M15.477 12.89 17 22l-5-3-5 3 1.523-9.11"/></svg></div>';
    wrap.replaceWith(ph);
  }
};

function renderAchievements(content) {
  const achievements = content.achievements.filter(a => a.type === 'achievement');
  const certs = content.achievements.filter(a => a.type === 'certification');

  function achieveCard(a, idx) {
    const grad = ACHIEVEMENT_GRADIENTS[idx % ACHIEVEMENT_GRADIENTS.length];
    return `
      <div class="ach-card ach-card--win reveal reveal-delay-${(idx % 4) + 1}">
        <div class="ach-card__glow" style="background:${grad}"></div>
        <div class="ach-card__icon-wrap" style="background:${grad}">
          ${icon(a.icon)}
        </div>
        <div class="ach-card__body">
          <span class="ach-card__type achievement">🏆 Achievement</span>
          <h4 class="ach-card__title">${esc(a.title)}</h4>
          <p class="ach-card__desc">${esc(a.description)}</p>
        </div>
        <div class="ach-card__shine"></div>
      </div>
    `;
  }

  // Brand icons for cert issuers (linked PNG files)
  const ISSUER_ICONS = {
    'Google Play Academy': `<img src="res/icons/google-play.png" alt="Google Play Academy" />`,
    'Udemy': `<img src="res/icons/udemy.png" alt="Udemy" />`,
    'DPE University (Gradle)': `<img src="res/icons/gradle.png" alt="Gradle" />`,
  };

  function certCard(c, idx) {
    const isPdf = c.image && c.image.endsWith('.pdf');
    const delay = (idx % 4) + 1;
    const credUrl = c.credentialUrl || '#';
    const issuerColor = c.issuerColor || '#2563EB';

    const previewHtml = isPdf
      ? `<div class="cert-card__pdf-preview">
           <div class="cert-card__pdf-icon">${icon('file-text')}</div>
           <span class="cert-card__pdf-label">Certificate PDF</span>
         </div>`
      : c.image
        ? `<div class="cert-card__img-wrap">
             <img src="${c.image}" alt="${esc(c.title)}" class="cert-card__img" loading="eager"
               onerror="window.certImgError(this)" />
             <div class="cert-card__img-overlay"></div>
           </div>`
        : `<div class="cert-card__pdf-preview"><div class="cert-card__pdf-icon">${icon('award')}</div></div>`;

    const validUntilHtml = c.validUntil
      ? `<span class="cert-meta__valid">Valid until ${esc(c.validUntil)}</span>` : '';
    const hoursHtml = c.hours
      ? `<span class="cert-meta__hours">${icon('clock')} ${esc(c.hours)}</span>` : '';

    return `
      <div class="cert-card reveal reveal-delay-${delay}">
        <a href="${credUrl}" target="_blank" rel="noopener noreferrer" class="cert-card__preview-link">
          ${previewHtml}
        </a>
        <div class="cert-card__body">
          <div class="cert-card__issuer-row">
            <span class="cert-card__issuer-logo">${ISSUER_ICONS[c.issuer] || `<svg viewBox="0 0 24 24" width="18" height="18"><rect width="24" height="24" rx="4" fill="${c.issuerColor||'#2563EB'}"/><path d="M12 6l1.5 4.5H18l-3.75 2.73 1.43 4.4L12 15.18l-3.68 2.45 1.43-4.4L6 10.5h4.5z" fill="#fff"/></svg>`}</span>
            <span class="cert-card__issuer">${esc(c.issuer || 'Certificate')}</span>
          </div>
          <h4 class="cert-card__title">${esc(c.title)}</h4>
          <p class="cert-card__desc">${esc(c.description)}</p>
          <div class="cert-card__meta">
            <span class="cert-meta__date">${icon('calendar')} ${esc(c.date || '')}</span>
            ${hoursHtml}
            ${validUntilHtml}
          </div>
          <a href="${credUrl}" target="_blank" rel="noopener noreferrer" class="cert-card__btn">
            ${icon('external-link')} View Certificate
          </a>
        </div>
      </div>
    `;
  }


  document.getElementById('achievements').innerHTML = `
    <div class="container">
      <div class="section-header">
        <div class="section-label">${icon('award')} Achievements</div>
        <h2 class="section-title">Achievements & Certifications</h2>
        <p class="section-subtitle">Recognition, impact metrics, and continuous learning milestones.</p>
      </div>
      <div class="ach-section-label">🏆 Achievements</div>
      <div class="ach-grid ach-grid--achievements">${achievements.map((a,i) => achieveCard(a,i)).join('')}</div>
      <div class="ach-section-label ach-section-label--cert">📜 Certifications</div>
      <div class="cert-grid">${certs.map((c,i) => certCard(c,i)).join('')}</div>
    </div>
  `;
}

// ── RENDER: EDUCATION ──────────────────────────────────────
function renderEducation(content) {
  const cards = content.education.map(edu => {
    const bullets = (edu.highlights || []).map(h =>
      `<div class="education-highlight">${esc(h)}</div>`
    ).join('');

    return `
      <div class="education-card reveal">
        <div class="education-card__left">
          <div class="education-card__degree">${esc(edu.degree)}</div>
          <div class="education-card__inst">${esc(edu.institution)}</div>
          <div class="education-highlights">${bullets}</div>
        </div>
        <div class="education-card__right">
          <div class="education-period">${icon('calendar')} ${esc(edu.period)}</div>
          <div class="education-gpa">${esc(edu.gpa)}</div>
          <div class="education-gpa-label">GPA</div>
        </div>
      </div>
    `;
  }).join('');

  document.getElementById('education').innerHTML = `
    <div class="container">
      <div class="section-header">
        <div class="section-label">${icon('layers')} Education</div>
        <h2 class="section-title">Academic Background</h2>
      </div>
      ${cards}
    </div>
  `;
}

// ── RENDER: CONTACT ────────────────────────────────────────
function renderContact(content) {
  const { contact, personal } = content;

  const connectItems = [
    {
      icon: 'linkedin',
      label: 'LinkedIn',
      value: 'sai-srujan-thammishetti',
      href: personal.linkedin,
      color: '#0A66C2',
      bg: 'rgba(10,102,194,0.08)',
      border: 'rgba(10,102,194,0.2)',
      external: true,
    },
    {
      icon: 'github',
      label: 'GitHub',
      value: 'github.com/Srujan-github',
      href: personal.github,
      color: '#24292e',
      bg: 'rgba(36,41,46,0.06)',
      border: 'rgba(36,41,46,0.15)',
      external: true,
    },
    {
      icon: 'mail',
      label: 'Email',
      value: esc(personal.email),
      href: `mailto:${personal.email}`,
      color: '#2563EB',
      bg: 'rgba(37,99,235,0.06)',
      border: 'rgba(37,99,235,0.15)',
      external: false,
    },
    {
      icon: 'phone',
      label: 'Phone',
      value: esc(personal.phone),
      href: `tel:${personal.phone}`,
      color: '#059669',
      bg: 'rgba(5,150,105,0.06)',
      border: 'rgba(5,150,105,0.15)',
      external: false,
    },
    {
      icon: 'map-pin',
      label: 'Location',
      value: esc(personal.location),
      href: null,
      color: '#7C3AED',
      bg: 'rgba(124,58,237,0.06)',
      border: 'rgba(124,58,237,0.15)',
      external: false,
    },
  ];

  const connectCards = connectItems.map((item, i) => {
    const tag = item.href ? 'a' : 'div';
    const attrs = item.href
      ? `href="${item.href}"${item.external ? ' target="_blank" rel="noopener"' : ''}`
      : '';
    return `
      <${tag} class="connect-card reveal reveal-delay-${i + 1}" ${attrs}
        style="--card-color:${item.color}; --card-bg:${item.bg}; --card-border:${item.border};">
        <div class="connect-card__icon" style="color:${item.color}; background:${item.bg}; border-color:${item.border};">
          ${icon(item.icon)}
        </div>
        <div class="connect-card__info">
          <span class="connect-card__label">${esc(item.label)}</span>
          <span class="connect-card__value">${item.value}</span>
        </div>
        ${item.href ? `<span class="connect-card__arrow">${icon('arrow')}</span>` : ''}
      </${tag}>
    `;
  }).join('');

  document.getElementById('contact').innerHTML = `
    <div class="container">
      <div class="section-header">
        <div class="section-label">${icon('mail')} Contact</div>
        <h2 class="section-title">${esc(contact.heading)}</h2>
        <p class="section-subtitle" style="max-width:640px;">${esc(contact.subheading)}</p>
      </div>
      <div class="connect-grid">
        ${connectCards}
      </div>
      <div class="contact-cta reveal">
        <a class="btn btn-primary btn-lg" href="${contact.ctaHref}">
          ${icon('mail', 'btn-icon')} ${esc(contact.ctaLabel)}
        </a>
        <a class="btn btn-secondary btn-lg" href="${contact.secondaryHref}" target="_blank" rel="noopener">
          ${icon('download', 'btn-icon')} ${esc(contact.secondaryLabel)}
        </a>
      </div>
    </div>
  `;
}

// ── RENDER: FOOTER ─────────────────────────────────────────
function renderFooter(content) {
  const { footer, personal, nav } = content;

  const footerLinks = nav.links.map(l =>
    `<a class="footer__link" href="${l.href}">${esc(l.label)}</a>`
  ).join('');

  document.getElementById('footer').innerHTML = `
    <div class="footer__top">
      <div class="container">
        <div class="footer__grid">
          <div class="footer__brand">
            <div class="footer__logo">${esc(nav.logo)}</div>
            <p class="footer__tagline">${esc(personal.tagline)}</p>
            <p class="footer__desc">Senior Android Developer based in ${esc(personal.location)}, building world-class mobile experiences with Kotlin, Jetpack Compose & KMM.</p>
            <div class="footer__socials">
              <a class="footer__social" href="${personal.linkedin}" target="_blank" rel="noopener" aria-label="LinkedIn">
                ${icon('linkedin')}
              </a>
              <a class="footer__social" href="${personal.github}" target="_blank" rel="noopener" aria-label="GitHub">
                ${icon('github')}
              </a>
              <a class="footer__social" href="mailto:${personal.email}" aria-label="Email">
                ${icon('mail')}
              </a>
              <a class="footer__social" href="tel:${personal.phone}" aria-label="Phone">
                ${icon('phone')}
              </a>
            </div>
          </div>
          <div class="footer__nav-col">
            <h4 class="footer__col-title">Navigation</h4>
            <div class="footer__links">
              ${footerLinks}
            </div>
          </div>
          <div class="footer__contact-col">
            <h4 class="footer__col-title">Get in Touch</h4>
            <div class="footer__contact-items">
              <a class="footer__contact-item" href="mailto:${personal.email}">
                ${icon('mail')} ${esc(personal.email)}
              </a>
              <a class="footer__contact-item" href="tel:${personal.phone}">
                ${icon('phone')} ${esc(personal.phone)}
              </a>
              <span class="footer__contact-item">
                ${icon('map-pin')} ${esc(personal.location)}
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="footer__bottom">
      <div class="container">
        <p class="footer__note">${esc(footer.note)}</p>
        <p class="footer__copy">&copy; ${footer.year} ${esc(personal.name)}. All rights reserved.</p>
      </div>
    </div>
  `;
}

// ── BACK TO TOP BUTTON ─────────────────────────────────────
function renderBackToTop() {
  const btn = document.createElement('button');
  btn.id = 'backToTop';
  btn.className = 'back-to-top';
  btn.setAttribute('aria-label', 'Back to top');
  btn.innerHTML = ICONS['arrow-up'] || '↑';
  document.body.appendChild(btn);

  window.addEventListener('scroll', () => {
    btn.classList.toggle('visible', window.scrollY > 300);
  }, { passive: true });

  btn.addEventListener('click', () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  });
}

// ── TYPING ANIMATION ───────────────────────────────────────
function initTypingAnimation(words) {
  const el = document.getElementById('typingText');
  if (!el || !words || !words.length) return;

  let wordIndex  = 0;
  let charIndex  = 0;
  let isDeleting = false;
  let isPaused   = false;

  function type() {
    const current = words[wordIndex];

    if (isPaused) {
      isPaused = false;
      setTimeout(type, 1800);
      return;
    }

    if (!isDeleting) {
      el.textContent = current.substring(0, charIndex + 1);
      charIndex++;
      if (charIndex === current.length) {
        isDeleting = true;
        isPaused   = true;
        setTimeout(type, 60);
        return;
      }
      setTimeout(type, 80);
    } else {
      el.textContent = current.substring(0, charIndex - 1);
      charIndex--;
      if (charIndex === 0) {
        isDeleting = false;
        wordIndex  = (wordIndex + 1) % words.length;
      }
      setTimeout(type, 45);
    }
  }

  type();
}

// ── COUNTER ANIMATION ──────────────────────────────────────
function animateCounters() {
  document.querySelectorAll('[data-target]').forEach(el => {
    const target = parseInt(el.dataset.target, 10);
    const suffix = el.dataset.suffix || '';
    if (isNaN(target)) { el.textContent = el.dataset.target + suffix; return; }

    let start = 0;
    const duration = 1800;
    const step = target / (duration / 16);

    function update() {
      start = Math.min(start + step, target);
      el.textContent = Math.floor(start) + suffix;
      if (start < target) requestAnimationFrame(update);
    }
    update();
  });
}

// ── SCROLL REVEAL ──────────────────────────────────────────
function initScrollReveal() {
  const revealEls = document.querySelectorAll('.reveal, .reveal-left, .reveal-right');
  if (!revealEls.length) return;

  const observer = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.classList.add('visible');
        if (entry.target.querySelector('[data-target]')) {
          animateCounters();
        }
        observer.unobserve(entry.target);
      }
    });
  }, { threshold: 0.12, rootMargin: '0px 0px -50px 0px' });

  revealEls.forEach(el => observer.observe(el));
}

// ── NAV SCROLL BEHAVIOUR ───────────────────────────────────
function initNav() {
  const nav = document.getElementById('nav');
  if (!nav) return;

  window.addEventListener('scroll', () => {
    nav.classList.toggle('scrolled', window.scrollY > 20);
  }, { passive: true });

  const sections = document.querySelectorAll('section[id]');
  const navLinks = document.querySelectorAll('.nav__link[data-href]');

  function setActiveLink() {
    const scrollPos = window.scrollY + 120;
    sections.forEach(sec => {
      const top    = sec.offsetTop;
      const bottom = top + sec.offsetHeight;
      if (scrollPos >= top && scrollPos < bottom) {
        navLinks.forEach(link => {
          link.classList.toggle('active', link.dataset.href === `#${sec.id}`);
        });
      }
    });
  }

  window.addEventListener('scroll', setActiveLink, { passive: true });
  setActiveLink();

  const hamburger   = document.getElementById('hamburger');
  const mobileMenu  = document.getElementById('mobileMenu');

  if (hamburger && mobileMenu) {
    hamburger.addEventListener('click', () => {
      const open = hamburger.classList.toggle('open');
      mobileMenu.classList.toggle('open', open);
      hamburger.setAttribute('aria-expanded', open);
    });

    mobileMenu.querySelectorAll('a').forEach(link => {
      link.addEventListener('click', () => {
        hamburger.classList.remove('open');
        mobileMenu.classList.remove('open');
        hamburger.setAttribute('aria-expanded', false);
      });
    });
  }
}

// ── COUNTER TRIGGER ON HERO IN VIEW ───────────────────────
function initHeroCounters() {
  const heroStats = document.querySelector('.hero__stats');
  if (!heroStats) return;

  const obs = new IntersectionObserver((entries) => {
    if (entries[0].isIntersecting) {
      animateCounters();
      obs.disconnect();
    }
  }, { threshold: 0.5 });

  obs.observe(heroStats);
}

// ── MAIN RENDER ────────────────────────────────────────────
function renderAll(content) {
  try {
    renderNav(content);
    renderHero(content);
    renderAbout(content);
    renderSkills(content);
    renderExperience(content);
    renderProjects(content);
    renderAI(content);
    renderOpenSource(content);
    renderAchievements(content);
    renderEducation(content);
    renderContact(content);
    renderFooter(content);
    renderBackToTop();

    requestAnimationFrame(() => {
      initNav();
      initScrollReveal();
      initHeroCounters();
      initTypingAnimation(content.personal.typingWords);
    });

  } catch (err) {
    console.error('[Portfolio] Render error:', err);
    document.body.insertAdjacentHTML('afterbegin', `
      <div style="background:#FEE2E2;color:#DC2626;padding:1rem;font-family:monospace;position:fixed;top:0;left:0;right:0;z-index:9999;font-size:.875rem;">
        ⚠️ Portfolio render error: ${err.message} — Check console for details.
      </div>
    `);
  }
}

// ── BOOT ───────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', () => {
  if (typeof PORTFOLIO_CONTENT === 'undefined') {
    console.error('[Portfolio] PORTFOLIO_CONTENT not found. Make sure content.js is loaded before app.js.');
    return;
  }
  renderAll(PORTFOLIO_CONTENT);
});
